[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/log/containers/*.log
    Parser       docker
    Tag          kube.*

[FILTER]
    Name         rewrite_tag
    Match        kube.*
    Rule         $log .* ai_platform.log true

[OUTPUT]
    Name         elasticsearch
    Match        *
    Host         elasticsearch-master.default.svc.cluster.local
    Port         9200
    Index        ai-platform-logs
    Type         _doc